version: "3"
services:
  next:
    image: node:16.13.0
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    working_dir: /app
    stdin_open: true
    tty: true
