version: "3"
services:
  next:
    image: node:lts-buster-slim
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
